# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 从libuv说开来——libuv源码分析
email: xiaomaoln@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  协作共享
baseurl: "/libuv-source-analysis" # the subpath of your site, e.g. /blog
url: "http://paulran.github.io" # the base hostname & protocol for your site
github_username:  paulran

repository: paulran/libuv-source-analysis

# Build settings
markdown: kramdown
  
