# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 从libuv说开来
email: xiaomaoln@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  从libuv说开来 - llibuv源码分析
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paulran.github.io/libuv-source-analysis/" # the base hostname & protocol for your site
github_username:  paulran

# Build settings
markdown: kramdown
